apiVersion: v1
kind: Pod

metadata:
  name: pod-1
  # bind do servico com o pod
  labels:
    app: primeiro-pod
spec:
  containers:
    - name: container-pod-1
      image: nginx:latest
      ports: 
        - containerPort: 80
