# criando um servico para o pod 2
apiVersion: v1
kind: Service
metadata:
  name: svc-pod-2
spec:
  type: ClusterIP
  # fazendo a comunicação com o pod
  selector:
    app: segundo-pod
  ports:
    - port: 9000 # portaParaOuvur:portaParaDespachar
      targetPort: 80


## a porta que queremos ouvir é diferente da porta que queremos despachar