apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  ports:
    - port: 80
      #targetPort: <Target Port>
      nodePort: 30000 #definindo a porta externa
  selector:
    app: primeiro-pod
